baseURL: "https://danielkhir.github.io/"
title: Daniel Khir
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  tag: tags

params:
  env: production
  title: Daniel Khir
  description: "Personal website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Daniel Khir
  DateFormat: "January 2, 2006"
  defaultTheme: auto # auto, dark, light
  disableThemeToggle: false
  social: true

  ShowReadingTime: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  enableGitInfo: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/assets/favicon.ico"
    favicon16x16:  "/assets/favicon-16x16.png"
    favicon32x32:  "/assets/favicon-32x32.png"
    apple_touch_icon:  "/assets/apple-touch-icon.png"
    safari_pinned_tab:  "/assets/safari-pinned-tab.svg"

  # label:
  #   text: "danielkhir"
  #   icon: /apple-touch-icon.png
  #   iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "Hi, I'm Daniel. \U0001F44B"
    Content: |
      Currently doing my Master's in Computer Science at the [University of Augsburg](https://www.uni-augsburg.de). When I'm not sitting in Machine Learning lectures, I build data-driven AI applications at [inovex](https://inovex.de). I am a fast learner who enjoys working in agile environments. In my free time, I read science fiction and work on my homelab.

  socialIcons:
    - name: github
      url: "https://github.com/danielkhir"
    - name: linkedin
      url: "https://linkedin.com/in/danielkhir"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 10

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
